// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

function validate(rule, value) {
  return value.length !== 0;
}

function getError(rule, field) {
  return field + " is required";
}

function validateForm(model) {
  return $$Array.map((function (record) {
                var isValid = record[/* value */1].length !== 0;
                var error = record[/* name */0] + " is required";
                return /* record */[
                        /* name */record[/* name */0],
                        /* error */isValid ? undefined : error
                      ];
              }), model);
}

exports.validate = validate;
exports.getError = getError;
exports.validateForm = validateForm;
/* No side effect */
