// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Input$ReactTemplate = require("./Input.bs.js");
var TextArea$ReactTemplate = require("./TextArea.bs.js");

var component = ReasonReact.reducerComponent("ContactForm");

function getChangeValue($$event) {
  return $$event.target.value;
}

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              return React.createElement("div", {
                          className: "w-screen h-screen flex content-center justify-center items-center"
                        }, React.createElement("form", {
                              className: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
                            }, ReasonReact.element(undefined, undefined, Input$ReactTemplate.make("Full Name", "text", state[/* name */0], (function ($$event) {
                                        return Curry._1(send, /* UpdateForm */[/* record */[
                                                      /* name */$$event.target.value,
                                                      /* email */state[/* email */1],
                                                      /* description */state[/* description */2]
                                                    ]]);
                                      }), /* array */[])), ReasonReact.element(undefined, undefined, Input$ReactTemplate.make("Reason", "text", state[/* email */1], (function ($$event) {
                                        return Curry._1(send, /* UpdateForm */[/* record */[
                                                      /* name */state[/* name */0],
                                                      /* email */$$event.target.value,
                                                      /* description */state[/* description */2]
                                                    ]]);
                                      }), /* array */[])), ReasonReact.element(undefined, undefined, TextArea$ReactTemplate.make("Description", state[/* description */2], (function ($$event) {
                                        return Curry._1(send, /* UpdateForm */[/* record */[
                                                      /* name */state[/* name */0],
                                                      /* email */state[/* email */1],
                                                      /* description */$$event.target.value
                                                    ]]);
                                      }), /* array */[])), React.createElement("div", {
                                  className: "flex items-center justify-between"
                                }, React.createElement("button", {
                                      className: "bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                                    }, "Send"))));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* name */"",
                      /* email */"",
                      /* description */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              if (action) {
                return /* Update */Block.__(0, [action[0]]);
              } else {
                return /* NoUpdate */0;
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.getChangeValue = getChangeValue;
exports.make = make;
/* component Not a pure module */
