// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("TextArea");

var labelClassList = /* array */[
  "block",
  "text-grey-darker",
  "text-sm",
  "font-bold",
  "mb-2"
];

var inputClassList = /* array */[
  "shadow",
  "appearance-none",
  "border",
  "rounded",
  "w-full",
  "py-2",
  "px-3",
  "text-grey-darker",
  "leading-tight",
  "focus:outline-none",
  "focus:shadow-outlin"
];

function make(label, value, onChange, invalid, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: invalid ? "rr-input rr-input__invalid" : "rr-input"
                        }, React.createElement("label", {
                              className: "rr-input__label"
                            }, label), React.createElement("textarea", {
                              className: "rr-input__field",
                              value: value,
                              onChange: onChange
                            }));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.labelClassList = labelClassList;
exports.inputClassList = inputClassList;
exports.make = make;
/* component Not a pure module */
